### ISSUE TITLE
Link to Security Champions Playbook

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-security-champions-guidebook#5]
Is this project linked to the [Security Champions Playbook](https://github.com/c0rdis/security-champions-playbook)?
I was not sure what the intentions were or whether these two OWASP projects are the same thing.

It would be good to link to https://github.com/c0rdis/security-champions-playbook if these are different projects

**Comment by robinvanloonOWASP** [comment]
There's no link between the projects. We found multiple initiatives around Security Champions. Ideally we'll provide links to interesting projects out there. For now we are focusing on the initial content and will consider your feedback in a later stage of the project.

**Comment by jgadsden** [comment]
Sure - thanks @robinvanloonOWASP , I can close this issue now

**Comment by robinvanloonOWASP** [comment]
@jgadsden References have been added [here](https://securitychampions.owasp.org/references/). Thank you for the suggestion!

**Comment by jgadsden** [comment]
BTW, I have raised in issue [Add Security Champions Guide to wayfinder #57](https://github.com/OWASP/www-project-integration-standards/issues/57) in the OWASP Integration Standards project
